### ISSUE TITLE
recommended grep command doesn't work for utf8

### ISSUE THREAD

**Issue by Shooter3k** [0xVavaldi/gramify#1]
please change this:
print("cat output_file.txt | sort | uniq -c | sort -rn | grep -oP '^ *[0-9]+ \\K.*' > sorted_output.txt")
to this:
print("cat output_file.txt | sort | uniq -c | sort -rn | grep -oaP '^ *[0-9]+ \\K.*' > sorted_output.txt")

**Comment by 0xVavaldi** [comment]
Modified in https://github.com/0xVavaldi/gramify/commit/fae0fe42f03798550a2f583f485f066b1e6a94ed
