### ISSUE TITLE
Improved Recommended Command

### ISSUE THREAD

**Issue by superevr** [0xVavaldi/gramify#4]
https://github.com/0xVavaldi/gramify/blob/64ef8cfb9edb86419051a4b4b819ed0fa079f107/gramify.py#L792-L794

I suggest updating this recommendation so that it is more likely to work as expected.
`cut -c9-` cuts at the 9th character position. But the size of each row can vary; `uniq -c` adds padding before the number and the number may be large depending on how large the gramify output is.

```zsh
% echo "password" | uniq -c | sort -rn | awk '($1 >=1)' | cut -c9-
sword
```

A simple way to do this in awk would be to use `{print $2}`, but that would remove any ngrams with a space.

So the solution I found is to use a bit more complex awk command:
```awk
awk '{if ($1 >=1) {$1=""; print substr($0, index($0, $2))}}'
```

You can try it out with different variations with this test command:
```zsh
% printf -- 'pass word\n%.0s' {1..99999} | uniq -c | sort -rn | awk '{if ($1 >=1) {$1=""; print substr($0, index($0, $2))}}'
pass word
```

**Comment by superevr** [comment]
It looks like my problem was actually caused by using the version of the `uniq` command in MacOS. Gnu uniq uses a more standard pattern of padding.

So as a workaround, make sure to use gnu uniq from coreutils.

**Comment by 0xVavaldi** [comment]
https://github.com/0xVavaldi/gramify/commit/99daaf10647ff4c541be5743b2d45e6985b0de01
